#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * Macros for device 'PACMAN_PIO', class 'altera_avalon_pio'
 * The macros are prefixed with 'PACMAN_PIO_'.
 * The prefix is the slave descriptor.
 */
#define PACMAN_PIO_COMPONENT_TYPE altera_avalon_pio
#define PACMAN_PIO_COMPONENT_NAME PACMAN_PIO
#define PACMAN_PIO_BASE 0x3080
#define PACMAN_PIO_SPAN 16
#define PACMAN_PIO_END 0x308F
#define PACMAN_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define PACMAN_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PACMAN_PIO_CAPTURE 0
#define PACMAN_PIO_DATA_WIDTH 16
#define PACMAN_PIO_DO_TEST_BENCH_WIRING 0
#define PACMAN_PIO_DRIVEN_SIM_VALUE 0
#define PACMAN_PIO_EDGE_TYPE NONE
#define PACMAN_PIO_FREQ 50000000
#define PACMAN_PIO_HAS_IN 0
#define PACMAN_PIO_HAS_OUT 1
#define PACMAN_PIO_HAS_TRI 0
#define PACMAN_PIO_IRQ_TYPE NONE
#define PACMAN_PIO_RESET_VALUE 0

/*
 * Macros for device 'BUTTON_PIO', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME BUTTON_PIO
#define BUTTON_PIO_BASE 0x3090
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x309F
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 0
#define BUTTON_PIO_DATA_WIDTH 4
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE NONE
#define BUTTON_PIO_FREQ 50000000
#define BUTTON_PIO_HAS_IN 0
#define BUTTON_PIO_HAS_OUT 1
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE NONE
#define BUTTON_PIO_RESET_VALUE 0

#endif